locale-info:
  language: ru
  country: RU

spring:
  messages:
    basename: /i18n/bundle
    encoding: UTF-8
  output:
    ansi:
      enabled: ALWAYS

      
message-source:
    basename: /i18n/bundle
    encoding: UTF-8

